2023-09-08 07:46:16 | ERROR - An error has been caught in function '_run', process 'MainProcess' (3526), thread 'MainThread' (140152745483328):- {}
Traceback (most recent call last):
  File "/home/runner/work/epic_weekly/epic_weekly/epic/src/claim.py", line 94, in <module>
    asyncio.run(run())
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
> File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/runner/work/epic_weekly/epic_weekly/epic/src/claim.py", line 90, in run
    await agent.execute(sequence=[claim_epic_games], headless=True)
  File "/home/runner/work/epic_weekly/epic_weekly/epic/src/services/models.py", line 113, in execute
    await container(context)
  File "/home/runner/work/epic_weekly/epic_weekly/epic/src/claim.py", line 79, in claim_epic_games
    await epic.claim_weekly_games(page, promotions)
  File "/home/runner/work/epic_weekly/epic_weekly/epic/src/services/agents/epic_games.py", line 196, in claim_weekly_games
    await payment_btn.click()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 15634, in click
    await self._impl_obj.click(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 160, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 489, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for frame_locator("xpath=//iframe[@class='']").locator("xpath=//div[@class='payment-order-confirm']")
============================================================
